### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by rinalds98** [KTC96/ShoreCleanse#34]
### Story

As a **user**, I can **access the blog section** so that I can **read articles, stories and updates related to beach clean ups**.

### Acceptance Criteria

- The user can access valuable sources of information and inspiration about beach cleanups.
- Content that keeps the user informed about environmental conservation.

### Tasks

- [ ] A blog page that showcases blogs
- [ ] Each blog would have a thumbnail, headline and a brief description.
- [ ] Within the blog page there would be articles with text and images.
