### ISSUE TITLE
Deploy Website

### ISSUE THREAD

**Issue by rinalds98** [KTC96/ShoreCleanse#35]
### Story

As a **Website Owner**, I can **deploy the website** so that I can **I host my website online**.

### Acceptance Criteria

- Access website online.
- Users information is saved to the database so they can log in/ register.

### Tasks

- [ ] Create a new instance on 'ElephantSQL' that holds the Postgres database.
- [ ] Deploy the website to Heroku.
- [ ] Set up config vars.
- [ ] Set up Django settings for the ability to pull data from the Postgres database.
