### ISSUE TITLE
Create a navigation menu

### ISSUE THREAD

**Issue by Aylamccarthy** [KTC96/ShoreCleanse#9]
### Story

As a **user**, I can **use a navigation menu** so that I can **easily navigate through the website content**.

### Acceptance Criteria

- The navigation menu is clear and intuitive
- Relevant information of the website such as name, motto, and 'about us' section

### Tasks

- [ ] Create a navigation menu
- [ ] Add the website name, motto, and 'about us' section
- [ ]  Create custom pages for 404.html, 500.html and 403.html error messages
